name: Spiritual Guidance
favicon: null
layout_spectrum: 0.4921
typography_spectrum: 0.09112
title: Guiding You To A Higher Consciousness
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141510'
    - '#333532'
    - '#51565a'
    - '#85a737'
    - '#b5d75e'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
