name: Spiritual Guidance
favicon: null
layout_spectrum: 0.8511085535865277
typography_spectrum: 0.4943956302013248
title: Guiding You To A Higher Consciousness
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141510'
    - '#333532'
    - '#51565a'
    - '#85a737'
    - '#b5d75e'
  brandStrength: 1
  lightness: 0.17971824202686548
  saturation: 0.597348720068112
  rhythmicContrast: 0.8068871044088155
purpose: []
