analytics: {}
color:
  brandColors:
    - '#141510'
    - '#333532'
    - '#51565a'
    - '#85a737'
    - '#b5d75e'
  brandStrength: 0.670045
  lightness: 0.375
  rhythmicContrast: 1
  saturation: 0.5
cta: {}
layout_spectrum: 0.13671484892256558
name: Spiritual Guidance
opengraph: {}
purpose: []
typography_spectrum: 0.9873170598875731
