name: Spiritual Guidance
favicon: null
layout_spectrum: 0.54116
typography_spectrum: 0.09112
title: Guiding You To A Higher Consciousness - Click through an image to explore your mind
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141510'
    - '#333532'
    - '#51565a'
    - '#85a737'
    - '#b5d75e'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
